---
server:
  port: 8080
  contextPath:
---
spring:
  profiles: default
datasource:
  sampleapp:
    url: jdbc:h2:~/sampledb
    username: SA
    password:
    driverClassName: org.h2.Driver
    defaultSchema:
    maxPoolSize: 10
    hibernate:
      ddl-auto: none
      hbm2ddl.method: validate
      show_sql: true
      format_sql: true
      dialect: org.hibernate.dialect.H2Dialect

---
spring:
  profiles: prod
datasource:
  sampleapp:
    url: jdbc:postgresql://localhost/sampledb
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
    defaultSchema:
    maxPoolSize: 20
    hibernate:
      ddl-auto: none
      hbm2ddl.method: validate
      show_sql: true
      format_sql: true
      dialect: org.hibernate.dialect.PostgreSQLDialect

